export const environment = {
  production: true,
  monedasUrl:  'http://localhost:3000/hostienda/monedas/',
  proveedoresUrl: 'http://localhost:3000/hostienda/proveedores/',
  usuariosUrl: 'http://localhost:3000/hostienda/usuarios/',
  empresasUrl: 'http://localhost:3000/hostienda/empresas/',
  sucursalesUrl: 'http://localhost:3000/hostienda/sucursales/',
  compraMaterialesUrl: 'http://localhost:3000/hostienda/compras/',
  parametrosUrl: 'http://localhost:3000/hostienda/parametros/',
  tasasCambiosUrl: 'http://localhost:3000/hostienda/tasas/',
  materiaPrimaUrl: 'http://localhost:3000/hostienda/materiasprima/',
  preciosUrl: 'http://localhost:3000/hostienda/precios/',
  unidadesUrl: 'http://localhost:3000/hostienda/unidades/',
  inventarioUrl: 'http://localhost:3000/hostienda/inventarios/',
  productosUrl: 'http://localhost:3000/hostienda/productos/',
  GastosProductosUrl: 'http://localhost:3000/hostienda/gastos/productos/',
  CostosProductosUrl: 'http://localhost:3000/hostienda/costos/productos/',
};
