export const environment = {
  production: true,
  monedasUrl:  'http://localhost:3000/monedas/',
  proveedoresUrl: 'http://localhost:3000/proveedores/',
  usuariosUrl: 'http://localhost:3000/usuarios/',
  empresasUrl: 'http://localhost:3000/empresas/',
  sucursalesUrl: 'http://localhost:3000/sucursales/',
  compraMaterialesUrl: 'http://localhost:3000/compras/',
  parametrosUrl: 'http://localhost:3000/parametros/',
  tasasCambiosUrl: 'http://localhost:3000/tasas/',
  materiaPrimaUrl: 'http://localhost:3000/materiasprima/',
  preciosUrl: 'http://localhost:3000/precios/',
  unidadesUrl: 'http://localhost:3000/unidades/',
  inventarioUrl: 'http://localhost:3000/inventarios/',
  productosUrl: 'http://localhost:3000/productos/',
};
